### ISSUE TITLE
WebSocket Error after npm start

### ISSUE THREAD

**Issue by reddhouse** [flipace/lovli.js#12]
From the console:
![screen shot 2016-06-04 at 8 14 58 am](https://cloud.githubusercontent.com/assets/1303872/15800401/78947030-2a2c-11e6-991d-ea9ed9e3c695.png)

From my terminal:
webpack: bundle is now VALID.
Unhandled rejection TypeError: Cannot read property 'table' of null
    at createTodos.js:26:13
    at tryCatcher (/Users/justintuttle/Code/patrickneschkudla/lovli.js/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/justintuttle/Code/patrickneschkudla/lovli.js/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/justintuttle/Code/patrickneschkudla/lovli.js/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/justintuttle/Code/patrickneschkudla/lovli.js/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/justintuttle/Code/patrickneschkudla/lovli.js/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/Users/justintuttle/Code/patrickneschkudla/lovli.js/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/justintuttle/Code/patrickneschkudla/lovli.js/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate](/Users/justintuttle/Code/patrickneschkudla/lovli.js/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback](timers.js:514:5)

**Comment by flipace** [comment]
Hi, thanks for the report - it might be an issue with auth tokens. Can you try to clear your localStorage?

**Comment by reddhouse** [comment]
Yes indeed, clearing local storage takes care of the issue. Thanks!
