### ISSUE TITLE
Error after npm start

### ISSUE THREAD

**Issue by comerc** [flipace/lovli.js#19]
```
$ npm start

> lovli.js@0.8.0 start /home/aka/lovli.js
> babel-node bin/dev.js

Building client bundle [==============      ] 70% (0.0 seconds)
Webpack Dev Server listening on port 9095
Creating a pool connected to 127.0.0.1:28015
Creating a pool connected to 127.0.0.1:28015
Express listening at http://localhost:3000
info: Connecting to RethinkDB: localhost:28015
Building client bundle [===========         ] 57% (1.2 seconds)info: Index metadata synced.
Building client bundle [==========          ] 52% (1.3 seconds)info: Groups metadata synced.
info: Collections metadata synced.
Building client bundle [========            ] 42% (1.4 seconds)info: Metadata synced with database, ready for traffic.
Built client in 8.966s.
Hash: 5af6335290a32da2a457
Version: webpack 1.13.0
Time: 8973ms
                                 Asset     Size  Chunks             Chunk Names
  1478ddc649b1c6f9313f008b8bc70c70.png  17.2 kB          [emitted]  
  a247f4358b253516c32943603c4c5970.eot  76.2 kB          [emitted]  
  6c4c3504e3402b6f1b75332b796da253.svg   390 kB          [emitted]  
  9f5388fac608dfe77f4343d38abf122f.ttf   152 kB          [emitted]  
a1a450ea331a3fc89e867ecad963b6b2.woff2  71.8 kB          [emitted]  
 f84ffa8dd9706d3cf7c8e800372c0cc0.woff  90.1 kB          [emitted]  
                      client.bundle.js  1.99 MB       0  [emitted]  app
                            styles.css  2.53 kB       0  [emitted]  app
                  client.bundle.js.map  2.23 MB       0  [emitted]  app
                        styles.css.map  4.01 kB       0  [emitted]  app
chunk    {0} client.bundle.js, styles.css, client.bundle.js.map, styles.css.map (app) 1.71 MB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 3.94 kB [rendered]
Child extract-text-webpack-plugin:
                                   Asset     Size  Chunks       Chunk Names
    1478ddc649b1c6f9313f008b8bc70c70.png  17.2 kB               
    chunk    {0} extract-text-webpack-plugin-output-filename 2.36 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 8.98 kB [rendered]
webpack: bundle is now VALID.
Unhandled rejection TypeError: Cannot read property 'table' of null
    at /home/aka/lovli.js/source/server/jobs/createTodos.js:26:13
    at tryCatcher (/home/aka/lovli.js/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/aka/lovli.js/node_modules/bluebird/js/release/promise.js:509:31)
    at Promise._settlePromise (/home/aka/lovli.js/node_modules/bluebird/js/release/promise.js:566:18)
    at Promise._settlePromise0 (/home/aka/lovli.js/node_modules/bluebird/js/release/promise.js:611:10)
    at Promise._settlePromises (/home/aka/lovli.js/node_modules/bluebird/js/release/promise.js:690:18)
    at Async._drainQueue (/home/aka/lovli.js/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/aka/lovli.js/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/aka/lovli.js/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by flipace** [comment]
hi, which version of horizon was used in this case?

**Comment by comerc** [comment]
2.0 release.

**Comment by flipace** [comment]
thanks for the info, this probably due to the changes to table definitions in horizon 2.
lovli has not yet been updated for v2.

**Comment by nikitph** [comment]
any temporary workarounds?

**Comment by flipace** [comment]
you can just remove the code which retrieves the "internal table name" from the createTodos and deleteTodos scripts since there's no need for this lookup anymore in horizon 2
